image: Visual Studio 2022  # Образ Windows

environment:
  JAVA_HOME: C:\Program Files\Eclipse Adoptium\jdk-21.0.7.6-hotspot  # Путь без \bin\java.exe

branches:
  only:
    - master

install:
  - gradlew.bat wrapper
  - start /B java -jar ./artifacts/app-mbank.jar  # Фоновый запуск

build_script:
  - timeout /t 5 /nobreak > nul  # Пауза для старта сервера
  - gradlew.bat test --info  # Запуск тестов